# We want to execute the main Makefile for the firmware project,
# it will handle the build for us.
CRAZYFLIE_BASE := ../..


# We override the default OOT_CONFIG here, we could also name our config 
# to oot-config and that would be the default. 
OOT_CONFIG := $(PWD)/app-config

include $(CRAZYFLIE_BASE)/tools/make/oot.mk